"use client";

import { ReactNode } from "react";
import { Home, Fuel, ClipboardList, BarChart3, Settings } from "lucide-react";
import { ThemeSwitcher } from "./ThemeSwitcher";

const nav = [
  { label: "Dashboard", icon: Home },
    { label: "Shifts", icon: ClipboardList },
      { label: "Sales", icon: Fuel },
        { label: "Reports", icon: BarChart3 },
          { label: "Settings", icon: Settings },
          ];

          function NavItem({ item }: { item: (typeof nav)[number] }) {
            const Icon = item.icon;
              return (
                  <button
                        className="w-full flex items-center gap-3 px-3 py-2 rounded-xl hover:bg-[rgb(var(--muted))] transition"
                              type="button"
                                  >
                                        <Icon size={18} />
                                              <span className="text-sm">{item.label}</span>
                                                  </button>
                                                    );
                                                    }

                                                    export function Shell({ children }: { children: ReactNode }) {
                                                      return (
                                                          <div className="min-h-dvh premium-gradient">
                                                                <div className="mx-auto max-w-7xl">
                                                                        <div className="grid grid-cols-1 md:grid-cols-[280px_1fr] gap-4 p-3 md:p-5">
                                                                                  <aside className="hidden md:block">
                                                                                              <div className="rounded-2xl border border-[rgb(var(--border))] bg-[rgb(var(--card))] p-4 shadow-[0_10px_30px_rgba(0,0,0,0.08)]">
                                                                                                            <div className="flex items-center justify-between">
                                                                                                                            <div>
                                                                                                                                              <div className="text-sm opacity-80">Motorway Petroleum</div>
                                                                                                                                                                <div className="text-lg font-semibold">FMS</div>
                                                                                                                                                                                </div>
                                                                                                                                                                                                <ThemeSwitcher />
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                            <div className="mt-4 space-y-1">
                                                                                                                                                                                                                                            {nav.map((item) => (
                                                                                                                                                                                                                                                              <NavItem key={item.label} item={item} />
                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                  </aside>

                                                                                                                                                                                                                                                                                                                            <main className="rounded-2xl border border-[rgb(var(--border))] bg-[rgb(var(--card))] shadow-[0_10px_30px_rgba(0,0,0,0.08)]">
                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center justify-between p-4 border-b border-[rgb(var(--border))]">
                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                      <div className="text-sm opacity-80">Fuel Station Management</div>
                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-lg font-semibold">Dashboard</div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="md:hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <ThemeSwitcher />
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-4 md:p-6">{children}</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="md:hidden border-t border-[rgb(var(--border))] bg-[rgb(var(--card))]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-5 gap-1 p-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {nav.map((item) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const Icon = item.icon;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="flex flex-col items-center justify-center gap-1 p-2 rounded-xl hover:bg-[rgb(var(--muted))] transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  aria-label={item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Icon size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-[11px] opacity-80">{item.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }